// v6.3.1888
(function(r,n,V,N,W,v,x,E,ka,la,ma,A,aa,F,na,G,oa,pa){function t(a,b,c,d){return function(){a.call(b,c,d)}}function I(a){return"object"==typeof a}function Da(){for(var a=32,b="";a--;)b+=(0|16*W.random()).toString(16);return b}function J(a,b,c,d,e){(e=a.addEventListener)?e.call(a,b,c,0):a.attachEvent(d||"on"+b,c)}function qa(){return V&&"preview"==V.loadPurpose}function O(a,b){for(var c in a)a.hasOwnProperty(c)&&a[c]!==p&&b(a[c],c)}function Ea(a){var b=(typeof a).charAt(0);return"[object Array]"==
ba.call(a)?"a":"[object Date]"==ba.call(a)?"d":b}function P(a,b){var c=[];O(a,function(d,e){c.push(ka(e)+"="+ka(b?Ea(d)+("[object Date]"==ba.call(d)?+d:I(d)&&d?P(d,b):d):d))});return c.join("&")}function Q(a,b){if(!a)throw Error(b);}function Fa(a){X[ra]=a;return ra++}function Y(a,b){var c="path=/;",d=a.g(6);d&&(c+="domain="+d+";");return{m:function(e,f){a.g(1,1)&&(n.cookie=e+"="+f+";expires="+((new v(+new v+(b?6E10:6E4))).toGMTString()+";")+c)},A:function(e){if(a.g(1,1))return(n.cookie.match("(^|;)\\s*"+
e+"=([^;]*)")||[])[2]||p},ba:function(e){n.cookie=e+"=;expires="+((new v(0)).toGMTString()+";")+c}}}function R(a){function b(){var g=d[G];g&&(d[G]=g[A](":_GS_:")[0])}var c;if(R[a])return R[a];var d=r.top;R[a]=c=function(){b();d[G]=(d[G]||"")+":_GS_:"+[a,c.f,c.I]};try{var e=d[G]||"";if(-1!=e[pa](":_GS_:")){var f=e[A](":_GS_:")[1][A](",");f[0]==a&&(c.f=f[1]||"",c.I=f[2]||"")}b()}catch(g){d={}}return c}function sa(a,b){var c=n[oa]("head")[0],d=n[ma]("script"),e=+new v;d.onerror=function(){100>+new v-
e&&b&&b()};d.src=a;c.appendChild(d);return function(){d&&c.removeChild(d);d=null}}function K(a){var b=B.c;b||(b=B.c=function(c){b.q.push(c)},b.q=[]);return b(a)}function ta(a,b){K(b);var c=B.c;c.c||(c.c=[2,a.b,a.g(15),a.g(11),a.g(6)]);a=(a.g(15)||{}).js||"https://js.gs-chat.com/chat.js";b=b[0];ua||(ua=1,sa(a+(b?"?"+b.v:"")))}function Ga(a){S(a,"chat",{},function(b){b&&(b[0]&&(b[0].notrack=1),ta(a,b))})}function L(a){function b(q){f.m(d,g.f=q?"":[l,548*y.D+2019,379*y.B+4621,+new v].join(":"));a.s(11,
q?0:l)}function c(q){z&&"-"!==z?(f.m(e,z+(C?"|"+C:"")),K(["i",a.b,z,C,q])):(f.m(e,""),K(["u",a.b,q]))}var d="gs_u_"+a.b,e="gs_v_"+a.b,f=Y(a,1),g=R(a.b),h=(f.A(d)||g.f||"")[A](/(?::|%3A)/),k=1,l=a.g(11,h[0])||(k=0,Da()),m=((h[1]||2019)-2019)/548,H=((h[2]||4621)-4621)/379;h=(h[3]||0)/1E3;var z=a.g(13),C=a.g(14);var y={f:l,C:z,D:m,B:H,ia:~~h,pa:k,fa:function(q,Ha){y.B+=+q;y.D+=+Ha;b()},W:function(q){z=y.C=q;c(1)},qa:b,na:function(){var q=f.A("gs_p_"+a.b)||g.I;f.ba("gs_p_"+a.b);return a.i!==p?a.i:q},
M:C,ra:function(q){Q(/^[0-9a-f]{64}$/.test(q),"Invalid auth signature");C=y.M=q;c(1)}};c();return y}function S(a,b,c,d,e,f){var g=t,h=x(function(){g();ca=(ca+1)%da[F];c.et&&(c.et=0);c.rt=1;--e&&S(a,b,c,d,e,f)},5E3),k=L(a);c.cb=Fa(function(l,m){g();E(h);d(l,m)});c.a=a.b;c.au=k.M;c.id=k.f;c.cid=k.C;c.tv=la;k=b+"?"+P(c);g=sa((Ia?"http":"https")+"://"+("chat"==b?b:da[ca])+".gosquared.com/"+k,f)}function Ja(a){var b=n[ma]("a");b.href=a||r.location.href;return b.href}function va(a,b,c){b=Ja(b);a.g(7,1)||
(b=b[aa](/\?([^#]*)/,function(d,e){e=e[A]("&");d=[];for(var f=0;f<e[F];f++)"utm_"===e[f].slice(0,4)&&d.push(e[f]);return d[F]?"?"+d.join("&"):""}));a.g(8)||(b=b[aa](/#.*$/,""));return{sa:b,t:c!==p?c:n.title,U:/^file:/.test(b)||/\/\/localhost[\/:]/.test(b+"/"),T:/fb_xd_(bust|fragment)/.test(b)}}function wa(a,b){if(a.L){var c=va(a);!a.g(9)&&c.U||c.T||qa()||(b=P(a.h,1))&&S(a,"prop",{cp:b},t,5)}else x(function(){wa(a)},100)}function xa(a,b,c){var d=a.h=a.h||{};Q(b||I(c),"Not an object");b?d[b]=c:d=a.h=
c;!a.V&&a.L&&(a.V=x(function(){wa(a);a.V=0},5))}function Ka(){var a=0,b=0;N&&(a=N.width,b=N.height);var c=(c=r.orientation)&&(c+360)%180;return{K:c?b:a,J:c?a:b,$:N&&N.colorDepth||"-",ha:V.language||V.browserLanguage||"-",aa:n.characterSet||n.charSet||"-",ca:r.devicePixelRatio||1,ja:(new v).getTimezoneOffset()}}function ea(){function a(f){return r["inner"+f]||c&&c[e="client"+f]||d&&d[e]}function b(f){return W.max(d[e="scroll"+f]|0,c[e]|0,d[e="offset"+f]|0,c[e]|0,d[e="client"+f]|0,c[e]|0)}var c=n.documentElement,
d=n.body||c,e;return{Y:a("Width"),X:a("Height"),P:b("Width"),O:b("Height"),o:r.pageXOffset||c&&c.scrollLeft||0,u:r.pageYOffset||c&&c.scrollTop||0}}function ya(a){a.j&&(a.j=0,a.w=new v-a.F+(a.w||0))}function fa(a){E(a.ka);a.ka=x(t(ya,0,a),15E3);a.j||(a.j=1,a.F=new v)}function La(a){var b=a.w,c=new v;a.j&&(b+=c-a.F,a.F=c);a.w=0;return b}function Ma(a){fa(a);var b=ea();b.u>a.H&&(a.H=b.u);b.o>a.G&&(a.G=b.o)}function Na(a){var b=t(fa,0,a);J(n,"mousemove",b);J(n,"keydown",b);J(r,"scroll",t(Ma,0,a));J(n,
"focus",b,"focusin");J(n,"blur",t(ya,0,a),"focusout")}function Oa(a){a=a.g(10,n.referrer);var b;!a||/^(chrome|about|file):/.test(a)||/^\[.*\]$/.test(a)?a="-":b=a[aa](/^.*?\/\//,"")[pa](location.host);return{S:+(0<=b&&8>=b),oa:a}}function Z(a,b,c,d){if(a.i!==p){if(!c){var e=ea();c={vw:e.Y,vh:e.X,dw:e.P,dh:e.O,st:e.u,sl:e.o,mst:a.H,msl:a.G}}c.i=a.i;c.e=b;c.et=La(a);w&&(c.bc=1);a.ea&&(c.rc=1);S(a,"ping",c,function(f){d&&d();E(a.l);a.l=x(t(Z,0,a),[7E3,12E3][a.ma++]||17500+5E3*W.random());f&&K(["c",a.b])},
5)}else x(function(){Z(a,b,c,d)},5E3)}function Pa(a){if(a.i!==p){var b=Y(a);a.g(1,1)?b.m("gs_p_"+a.b,a.i):(b=R(a.b),b.I=a.i,b())}}function ha(a,b,c){Q(a,"Event name is required");b&&b.call&&(c=b,b=p);if(b===""+b||b===+b)b={caption:b};a={gs_evt_name:a,d:P(b||{},1)};Z(this,"event",a,c)}function ia(a,b,c){a&&a.call&&(c=a,a=p);b&&b.call&&(c=b,b=p);var d=this;b=va(d,a,b);var e=Oa(d),f=d.i===p&&!e.S,g=d.L=L(d),h=Ka(),k=ea(),l=d.g(5);g.fa(1,f);E(d.l);d.w=0;d.j=0;fa(d);if(!(!d.g(9)&&b.U||b.T||qa()||h.K&&
h.J&&10>h.K&&10>h.J)){d.H=k.u;d.G=k.o;var m={cs:h.aa,cd:h.$,la:h.ha,sw:h.K,sh:h.J,dp:h.ca,pu:b.sa,pt:b.t||"-",ri:e.S,ru:e.oa,re:g.pa,vi:g.D,pv:g.B,lv:g.ia,vw:k.Y,vh:k.X,dw:k.P,dh:k.O,st:k.u,sl:k.o,un:d.g(3),pp:g.na(),ec:l,aip:d.g(2)?1:p,tz:h.ja};d.h&&(m.cp=P(d.h,1));d.da||!1===d.g(15)||(m.rc=1,d.da=1);w&&(d.uid=g.f,m.bc=1);d.ma=0;var H;S(d,"pv",m,function(z,C){z!==p&&(d.i=z,E(d.l),d.l=x(t(Z,0,d),5E3),c&&c());C&&!H&&(ta(d,C),d.ea=1)},5,function(){m.rc&&!H&&(H=1,Ga(d))});d.i!==p?a!==p&&(d.i=p):(x(t(Na,
0,d),500),J(r,"beforeunload",t(Pa,0,d)))}}function za(a){var b="gs_v_"+a,c=this,d=[];d[12]=c.b=a;c.s=function(f,g,h){4==f&&(xa(c,h,g),g&&!c.R&&(h=g.id,g=g.email,!h&&g&&(h="email:"+g),h&&(c.R=h,L(c).W(h))),g=c.h);13==f&&(xa(c,"id",g),g=(c.R=g)||"-",L(c).W(g));14==f&&L(c).ra(g);d[f]=g};c.g=function(f,g){function h(){var k=Y(c,1).A(b);if(/\|[0-9a-f]{32,64}/.test(k)){k=k[A]("|");var l=k.pop();k=k.join("|")}return{Z:l,C:k}}return f in d?d[f]:13===f?h().C||g:14===f?h().Z||g:g};var e;c.ga=function(){e=x(t(ia,
c),20)};c.N=function(){E(c.l);E(e)}}function ja(a,b,c){if(!a)for(a in u)return u[a];if(u[b||a])return u[b||a];a=u[b||a]=new za(a);c&&a.ga();return a}function M(a,b,c,d,e){b?a.call(u[b],c,d,e):O(u,function(f){a.call(f,c,d,e)})}function Qa(a,b,c,d){function e(l,m){m=m||(I(l)?l:{});I(l)||(m[G]=l);Q(m[G],"No Name");h.push(m);return k}function f(l){for(var m=0;m<l[F];)e(l[m++]);return k}function g(){M(function(){var l=Y(this,1),m="gs_t_"+this.b,H=l.A(m)||0;l.m(m,+new v);ha.call(this,"_transaction",{id:b,
pt:{ts:+H},i:h,d:c})},a)}!c&&I(b)&&(c=b,b=c.id);var h=[],k;d&&f(d);c&&c.track&&g();return k={id:b,addItem:e,addItems:f,track:g}}function Ra(a,b){!b&&I(a)&&(b=a,a=b.id,!a&&b.email&&(a="email:"+b.email));Q(a,"ID or email required");"__n/v_"!==a&&this.s(13,a);b&&this.s(4,b)}function B(a,b,c,d){if(a&&a.call)a();else if(/^GSN-.*-.$/.test(a))b!==""+b&&(c=b,b=0),ja(a,b,c||c===p);else if(X[a])X[a](b,c),delete X[a];else{var e=function(h,k,l){f?u[f].s(h,k,l):O(u,function(m){m.s(h,k,l)})};a=a[A](".");var f;
1<a[F]&&(f=a.shift());a=a[0];var g={usecookies:1,anonymizeip:2,visitorname:3,username:3,statuscode:5,cookiedomain:6,trackparams:7,trackhash:8,tracklocal:9,referrer:10,visitorid:13,visitor:4,clientid:11,auth:14,props:4,properties:4,chat:15};if(/transaction$/i.test(a))return Qa(f,b,c,d);if("get"==a)return c=g[(b+"")[na]()]||b,f?d=u[f].g(c):O(u,function(h){d=h.g(c)}),d;"set"==a?(a=(b+"")[A]("."),b=a.shift(),e(g[b[na]()]||b,c,a.join("."))):"track"==a?M(ia,f,b,c,d):"event"==a?M(ha,f,b,c,d):"cancel"==a?
M(function(){this.N()},f):"noCookies"==a?e(1,0):"anonymizeIP"==a?e(2,1):"tag"==a?e(3,b):"load"==a?b&&b():"auth"==a?e(14,b):"identify"==a?M(Ra,f,b,c,d):"alias"==a?e(13,b):"unidentify"==a?M(function(){if(this.g(13)||K(["e",this.b]))this.s(13),L(this).qa(1)}):"props"==a||"properties"==a?e(4,b):"chat"==a&&K([b,c,d])}}function Aa(a){B.apply({},a)}var p,T,U=r._gs||(T=1,function(){Ba.push(arguments)}),Ba=U.q||[];if(!U.v){var w=r.GoSquared,ba=Object.prototype.toString,X={},ra=0,da=["data","data2"],ca=0|W.random()*
da[F],Ia=/^http:/.test(location.href),ua,u={};if(w){O(w,function(a,b){"acct"==b?(ja(a,"_default",1),U(function(){function c(e){d[e.shift()].apply(d,e)}var d=w.DefaultTracker=u._default;if(b=w.q)for(;a=b.shift();)c(a);w.q={push:c};(b=w.load)&&b(d)})):"load"!=b&&"q"!=b&&U("set",b,a)});var D=za.prototype;D.TrackView=ia;D.TrackEvent=ha;D.Cancel=function(){this.N()};w.Tracker=ja;w.Cancel=t(B,0,"cancel")}r._gs=B;B.v=la;for(U.q={push:Aa};D=Ba.shift();)Aa(D);if(T){T=n[oa]("script");D=T[F];for(var Ca;D--;)(Ca=
T[D].getAttribute("data-gs"))&&B(Ca)}}})(window,document,navigator||{},screen,Math,Date,setTimeout,clearTimeout,encodeURIComponent,"6.3.1888","createElement","split","replace","length","toLowerCase","name","getElementsByTagName","indexOf");
